package com.todo.web;

import java.sql.SQLException;
import java.sql.Statement;

import org.hsqldb.Server;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.britesnow.snow.web.WebApplicationLifecycle;
import com.britesnow.snow.web.db.hibernate.HibernateDaoHelper;
import com.britesnow.snow.web.db.hibernate.HibernateSessionInViewHandler;
import com.google.inject.Inject;
import com.google.inject.Singleton;

@Singleton
public class HSQLLifeCycle implements WebApplicationLifecycle {
    
	public static Logger logger = LoggerFactory.getLogger(HSQLLifeCycle.class);
	
    @Inject
    private HibernateDaoHelper hibernateDaoHelper;
    
    @Inject
    HibernateSessionInViewHandler hibernateSessionInViewHandler;
    

    public HSQLLifeCycle(){
        
        Server server = new Server();
        server.setDatabaseName(0, "tododb");
        server.setDatabasePath(0, getClass().getResource("/")+"hqldb/tododb");
        server.start();
        try {
            Thread.sleep(800);
        } catch (InterruptedException e) {
        	logger.error(e.getMessage(), e);
        }  
        logger.debug("HSQLDB started...");
        
    }
    
    @Override
    public void init() {
        createTables();
    }

    @Override
    public void shutdown() {
        Statement statement = null;
        try {
            hibernateSessionInViewHandler.openSessionInView();
            System.out.println("HSQLDB stoped...");
            statement = hibernateDaoHelper.getConnection().createStatement();
            statement.executeUpdate("SHUTDOWN;");
        } catch (SQLException e) {
        	logger.error(e.getMessage(), e);
        } finally{
            if(statement != null){
                try {
                    statement.close();
                } catch (SQLException e) {
                	logger.error(e.getMessage(), e);
                }
            }
            hibernateSessionInViewHandler.closeSessionInView();
        }
    }
    
    private void createTables(){
        hibernateSessionInViewHandler.openSessionInView();
        Statement statement = null;
        try {
        	
            statement = hibernateDaoHelper.getConnection().createStatement();
            statement.executeUpdate("create table t_todo (id bigint GENERATED BY DEFAULT AS IDENTITY(START WITH 1) not null primary key,name varchar(100),bedone int, createdby_id bigint, created_date date,updatedby_id bigint,updated_date date)");
        
        } catch (SQLException e) {
        	logger.error(e.getMessage(), e);
        } finally{
            if(statement != null){
                try {
                    statement.close();
                } catch (SQLException e) {
                	logger.error(e.getMessage(), e);
                }
            }
            hibernateSessionInViewHandler.closeSessionInView();
        }
    }

}
